# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
        main:
            switch_user: true
            switch_user: {role: ROLE_ADMIN, parameter: _want_to_be_this_user}
            pattern:         .*
            form_login:
               default_target_path: /accueil
               provider:       fos_userbundle
               csrf_provider:  form.csrf_provider
               login_path:     /login
               use_forward:    false
               check_path:     /login_check
               failure_path:   null
            remember_me:
                key:         %secret%
                lifetime:    3600
                path:        /
            logout:
                path:   /logout
                target: /accueil
            anonymous:       true

   access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }