<?php

namespace SwaterLand\FilmBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;
use SwaterLand\FilmBundle\Entity\Bluray;

/**
 * BlurayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlurayRepository extends EntityRepository
{
}
