<?php

namespace SwaterLand\QualiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualiteRepository extends EntityRepository
{
}
